[General]
ipv6 = false
bypass-system = true
skip-proxy = 192.168.0.0/16, 10.0.0.0/8, 172.16.0.0/12, localhost, *.local
bypass-tun = 192.168.0.0/16, 10.0.0.0/8, 172.16.0.0/12, localhost, *.local
dns-server = https://1.1.1.1/dns-query, https://8.8.8.8/dns-query

[Rule]
RULE-SET,https://raw.githubusercontent.com/rz6agx/iOS-Rule/main/Telegram.list,PROXY
RULE-SET,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Shadowrocket/Telegram/Telegram.list,PROXY
FINAL,DIRECT

[Host]
localhost = 127.0.0.1
